### ISSUE TITLE
Cropping / Editing (imagePicker.allowsEditing)

### ISSUE THREAD

**Issue by xiaosongshu** [floriangbh/FacebookImagePicker#12]
Is there any way to crop the selected photo into a square image after selecting from an album? Similar to imagePicker.allowsEditing = true? Awesome work!

**Comment by floriangbh** [comment]
Hello, not actually ! But maybe in futur release.
Actually I'm using this library for crop image in my project : https://github.com/TimOliver/TOCropViewController

**Comment by xiaosongshu** [comment]
@terflogag Man that's a shame. Was hoping there might be something quick like forcing the image into an `UIImagePicker` since it already has native square cropping. TOCropViewController looks neat, (albeit maybe too powerful for my use case). Any suggestions for Swift 3?

Edit: ended up using TOCropViewController and it works flawlessly. Thanks again @terflogag
