### ISSUE TITLE
support collection picker

### ISSUE THREAD

**Issue by aldocyanlabs** [floriangbh/FacebookImagePicker#14]
Hi happy to finally found fbimagepicker that written in swift! Btw I've question, does this lib support multiple photos picker like oceanlabs?

**Comment by floriangbh** [comment]
Hello ! Not to this version, but this features is in the todo list (https://github.com/terflogag/FacebookImagePicker/issues/3), feel free to make PR :)

**Comment by floriangbh** [comment]
It now support multiple selection for one album, maybe more in futur release !
