### ISSUE TITLE
Not getting latest committed files in version 1.1.8

### ISSUE THREAD

**Issue by SarthakShah31** [floriangbh/FacebookImagePicker#20]
I have installed using pods, and i checked it's version. It's shopwing me latest version 1.1.8 
but in projects, i am not able to see structure like Model, View, Controller as in your demo as well as not getting some files like GBHSelectedView etc. Please see screenshots from below links.

Screenshot From your demo:-
http://prntscr.com/f71615

Screenshot of pod installation:-
http://prntscr.com/f714qo

Screenshot of my Demo:-
http://prntscr.com/f714qo

Please let me know what's wrong i did.

**Comment by floriangbh** [comment]
Hello ! 

Sorry I just forgot to finish and update the pod version for the v1.2, which will contain multiple selection.
Hope I will finish it this weekend, this is in my todo list :-) 

You can use this https://github.com/terflogag/FacebookImagePicker/releases/tag/1.1.8 to have the original v1.1.8 repository. 

Next time I'll use another branch to avoid this problem.
