### ISSUE TITLE
Tagged photos

### ISSUE THREAD

**Issue by nico75005** [floriangbh/FacebookImagePicker#21]
Would that be possible to get the photo where I am tagged and all of them gathered in "an album" called "Photos of me" for example?

Cheers

**Comment by floriangbh** [comment]
Hello @nico75005, I think not actually with this version, I will take a look when I have some free time  !

**Comment by Elshad** [comment]
@terflogag @nico75005  There is solution
[#26](https://github.com/terflogag/FacebookImagePicker/pull/26)

**Comment by floriangbh** [comment]
I will update the pod this weekend 👍

**Comment by floriangbh** [comment]
Tagged photos are now available with the 1.3.0. Don't forget to enable it (disable by default), see the customisation section !

**Comment by nico75005** [comment]
@terflogag The tagged photos are incomplete. A lot of photos are missing.
And would that be possible to get the number of pictures from the root like with other albums?

Thanks

**Comment by floriangbh** [comment]
When you said lot of photos are missing, you have only the first pictures ? Or some random pictures are missing ? 

I think display the number of picture isn't good idea. The tagged pictures isn't an regular album, so we don't have the number of picture like for the others albums. Then to have the number of picture we need to fetch ALL picture and apply count on it. And if there are 1k tagged pictures  the user need to wait the download even if we don't want open the tagged album....

**Comment by nico75005** [comment]
okay I thought there was a way to get the count without downloading. That's fine then.

Regarding the photos there, looks like it's some randoms pics ordered by time (latest ones first). I would say I get only a quarter of all of them. I thought at first that the photos there were just public ones but there are private ones as well.

**Comment by Elshad** [comment]
@nico75005 
There is not specific FB API to get tagged photos as Album. 
You will see photos as in link `https://www.facebook.com/{yourName}/photos_of`
