### ISSUE TITLE
White browser page after authorization

### ISSUE THREAD

**Issue by ramirez** [floriangbh/FacebookImagePicker#22]
When I launch the picker, I always get the authorization page in Facebook. After the login and the permission agreement the web view is blank and the only button is "Done" which close and cancel the picker. Any ideas?

**Comment by floriangbh** [comment]
Hello, did you handle correctly the Facebook login call back url ? 

With : 
```swift
    // Needed for handle Facebook callback url
    func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any] = [:]) -> Bool {
        let sourceApplication = options[UIApplicationOpenURLOptionsKey.sourceApplication] as? String
        let annotation = options[UIApplicationOpenURLOptionsKey.annotation] as? String
        FBSDKApplicationDelegate.sharedInstance().application(app,
                                                              open: url,
                                                              sourceApplication: sourceApplication,
                                                              annotation: annotation)
        return true
    }
```

it seem's to be an Facebook SDK implementation error :)

**Comment by ramirez** [comment]
yes, I have the same in my appDelegate, but I'm still having the same issue.

**Comment by terflogag** [comment]
Cool :)

**Comment by floriangbh** [comment]
Humm, can't really help without more informations :(
Can you share with me your simple setup ? (In another repo for exemple)

**Comment by ramirez** [comment]
Sorry, I can share any code. My application does a login using the facebook framework, and that works ok, but when I the image picker, I get a white screen after allowing access to the application. I don't understand why it doesn't work, and how come it asks again for authorization when I use your component.

**Comment by ramirez** [comment]
Btw, I compared my setup in each point with the one on your example application, and everything is setup in the same way. I tried several different configurations, but it doesn't seem to work.

**Comment by ramirez** [comment]
It was my error. Somehow I was importing the FB kit twice. I fixed my dependency management and now it works like a charm. Thx.

**Comment by floriangbh** [comment]
Happy to hear that 👍
