### ISSUE TITLE
Multiple selection is not available

### ISSUE THREAD

**Issue by IlyaBaudin** [floriangbh/FacebookImagePicker#27]
Hello.

Check your documentation.
And find that library allow multiple selection. But not there is no this parameter in settings. 

It will be great if you add it.

Thanks.

**Comment by floriangbh** [comment]
Hello @IlyaBaudin :) 

The first line of the Customisation's section is about multiple section (https://github.com/terflogag/FacebookImagePicker#customisation) : 
```
// Multiple selection settings 
GBHFacebookImagePicker.pickerConfig.allowMultipleSelection = true // False by default  
```

Or maybe your not talking of this settings ?

**Comment by IlyaBaudin** [comment]
Thanks for your fast reply.

I install framework using Cocoapods and GBHFacebookImagePicker.pickerConfig hasn't got allowMultipleSelection option.

Screen in attachment.
![2017-08-31 11 03 50](https://user-images.githubusercontent.com/1227522/29912927-20d48a18-8e3c-11e7-9a6c-ebc96e5a59b3.png)

**Comment by IlyaBaudin** [comment]
So using cocoapods now i checked and it installed 1.1.8 version.

**Comment by floriangbh** [comment]
I just tried and the latest version using cocoa pods is 1.3.0 (https://cocoapods.org/pods/GBHFacebookImagePicker). 

Maybe clean and update Cocoapods & set `pod 'GBHFacebookImagePicker', '~> 1.3.0'` in your Podfile ?

**Comment by IlyaBaudin** [comment]
Updated pods solve my issue.
Thanks a lot. And thanks for you fast support.

**Comment by floriangbh** [comment]
Cool ! 👍
