### ISSUE TITLE
Integrate without pod config

### ISSUE THREAD

**Issue by mrsantran** [floriangbh/FacebookImagePicker#29]
Integrate without pod config

**Comment by floriangbh** [comment]
Hello,

FacebookImagePicker can't run without the Facebook SDK. If you want integrate it manually you need to also integrate the Facebook SDK manually. 
For FacebookImagePicker you can drag and drop the `GBHFacebookImagePicker/source` folder. The necessary asset are in the `Images` folder. 

Feel free to try and give me a feedback :)
