### ISSUE TITLE
Question: SelectedBorderWidth & SelectedBorderColor

### ISSUE THREAD

**Issue by pak-amsiq** [floriangbh/FacebookImagePicker#31]
Why is selectedBorderWidth & selectedBorderColor configuration removed?

Is it possible to apply the same functionality without settings these settings?

**Comment by floriangbh** [comment]
Removed since the https://github.com/terflogag/FacebookImagePicker/releases/tag/2.0. 

You can make PR to enable it. Careful to SwiftLint & make it disable by default to let the current style. :)

**Comment by pak-amsiq** [comment]
Alright - Please see https://github.com/floriangbh/FacebookImagePicker/pull/32
