### ISSUE TITLE
Swift/Objective-C Facebook asks for login twice, won't display photos

### ISSUE THREAD

**Issue by kornha** [floriangbh/FacebookImagePicker#36]
I am writing an iOS app, in which the base of the application is written in Objective-C. I however am writing a file in Swift, and am using this Swift Facebook image picker, with pod FBSDKCoreKit 4.29 and FBSDKLoginKit 4.29 in my podfile. My App delegate is also in Objective-C.

When I activate this FacebookImagePicker while using the app, I am again prompted to login with Facebook, and if I login the screen is white and blank. Any idea why?

**Comment by floriangbh** [comment]
Hello, 

Have you already the FBSDK installed before add this picker ? 

It look like a Facebook SDK setup issue. But I never tried it on objective-C projet, i will test it asap :-)

**Comment by kornha** [comment]
Hi,

Yes, I had the Facebook SDK installed and working before this. Let me know what you discover :)

**Comment by floriangbh** [comment]
I doesn't really have a time to make an Objective-C demo (didn't make any Obc-C since 4 years, so I don't really want to lost too much time to div back in 😝 ). Can you make an objective-c sample with this picker ? 

But in fact, nothing are done to work with Obj-C (there is no @objc exposition)...

**Comment by dani2906** [comment]
Hey, will this pod work with obj project?
