### ISSUE TITLE
No such module 'GBHFacebookImagePicker'

### ISSUE THREAD

**Issue by tcliff111** [floriangbh/FacebookImagePicker#37]
After including the library in the podfile and doing 'pod install' in terminal, terminal lists this library among the pods successfully installed.  However, I'm getting a 'no such module' error upon trying to import GBHFacebookImagePicker.  I have tried restarting Xcode and reinstalling the pod.  There was another issue with this error, but the poster closed it without a solution.

**Comment by floriangbh** [comment]
Hello,

It looks like a Cocoapods issue. Maybe you can try to delete the derived data, clean and build again ? 
You can also ping the other issue to ask at the poster.

**Comment by tcliff111** [comment]
Hi, thanks for the response!  I think there is an error in: GBHFacebookNavigationController: UINavigationController.  In the viewdidload for:
 if let tintColor = GBHFacebookImagePicker.pickerConfig.uiConfig.navTitleColor {
            self.navigationBar.titleTextAttributes = [
                NSAttributedStringKey.foregroundColor: tintColor
            ]
        }
it was saying that NSAttributedStringKey has no attribute foregroundColor, so maybe they changed it?  I commented out those 3 lines from "self.nav..." to "]"  and now it works.

**Comment by floriangbh** [comment]
Humm, maybe a Swift version issue, NSAttributedStringKey (https://developer.apple.com/documentation/foundation/nsattributedstringkey/1533563-foregroundcolor) was introduced with Swift 4. What is the Swift version of you project ? 
Maybe you need to force Swift 4 in your podfile ?

**Comment by tcliff111** [comment]
Ah.. yes that's probably it, my swift version is 3.2.  I'll either leave that part out or upgrade to Swift 4.  Thanks for the help!  Great library by the way, it's really helpful!
