### ISSUE TITLE
GalleryControlles does not conform

### ISSUE THREAD

**Issue by armatucuadro** [floriangbh/FacebookImagePicker#38]
Hey! Ive just installed it with cocoapods and it says the following when I instantiate the picker with the code:
picker.presentFacebookAlbumImagePicker(from: self, delegate: self)

Xcode throws the following error:

Argument type 'galleryController' does not conform to expected type 'GBHFacebookImagePickerDelegate'

Would you know what is happening? 

Thanks!

**Comment by floriangbh** [comment]
Hello @armatucuadro,

You need to implement the `GBHFacebookImagePickerDelegate` protocol (https://github.com/floriangbh/FacebookImagePicker#usage) in you `galleryController`.

**Comment by floriangbh** [comment]
I'm closing this issue, let me know if you have again this issue.
