### ISSUE TITLE
Convertion of GBHFacebook image

### ISSUE THREAD

**Issue by Appbazooka** [floriangbh/FacebookImagePicker#45]
I want to convert the GBHFacebook images from [GBHFacebookImage] into Nsdata for uploading  of images picked from album picker to JSONAPI. Please provide me with sufficient convertion codes and respond as soon as possible.

**Comment by floriangbh** [comment]
Hello,

You can map the image to your own custom object, or make a PR to make GBHFacebookImage compliant with NSCoding for example, I think it can work. Currently, I don't need this feature and I don't have time to work on this.
