### ISSUE TITLE
GBHFacebookImagePickerDelegate protocol implementation problem

### ISSUE THREAD

**Issue by mrduyu** [floriangbh/FacebookImagePicker#47]
Hi,

I added GBHFacebookImagePicker into my project using pod 'GBHFacebookImagePicker'. When I try to use, I face two problems.
1- I implemeted the protocol. It contains 4 methods. After implementation the error says that 
Type 'ImagePickerLauncher' does not conform to protocol 'GBHFacebookImagePickerDelegate'
Here is screenshot:
<img width="1335" alt="screen shot 2018-07-29 at 12 01 14" src="https://user-images.githubusercontent.com/40163745/43364661-52ec1066-9327-11e8-8a62-798ca768b1c9.png">

2- When I say fix the error above. It duplicates the method and starts giving another error
Invalid redeclaration of 'facebookImagePicker(imagePicker:successImageModels:errorImageModels:errors:)'
Here is screenshot:
<img width="1328" alt="screen shot 2018-07-29 at 12 05 52" src="https://user-images.githubusercontent.com/40163745/43364689-cbac3378-9327-11e8-9356-fc6ee43c2b9e.png">

How should I proceed?
Best regards,
Emre.

**Comment by floriangbh** [comment]
Hello Emre, 

It’s hard to tell where is the issue. It’s seems to be an Xcode issue.
Can you check the pod version ? 
Can you clean the derived data, clean the projet and implement the protocol ? 

If the problem persist provide a sample of your code. 

Florian

**Comment by mrduyu** [comment]
Hi,
It is weird. I updated Xcode version, cleaned project. It solved the issue.
Thanks.
Emre.
