### ISSUE TITLE
Please make compatible to FBSDKLoginKit 4.37.0 & FBSDKCoreKit 4.37.0

### ISSUE THREAD

**Issue by swapnil6132** [floriangbh/FacebookImagePicker#50]
Hello,

I am using your GBHFacebookImagePicker library. But I can't update FBSDKLoginKit as well as FBSDKCoreKit also. Because GBHFacebookImagePicker depends on FBSDKLoginKit ~> 4.34.0 and FBSDKCoreKit ~> 4.34.0.

Can you please update your library compatible to latest version FBSDK? So I can user your library with latest version of FBSDK. It will be really helpful for me.

Thank you,
Swapnil

**Comment by floriangbh** [comment]
Hello,

Please try the v2.4.1 :) 

Florian
