### ISSUE TITLE
Bump version

### ISSUE THREAD

**Issue by nitrag** [floriangbh/FacebookImagePicker#51]
CocoaPods version doesn't have the code with the fixes for Swift 4.2 (pushed 22 days ago). 

Please make a new release and push to CocoaPods.

Thanks!

**Comment by floriangbh** [comment]
Hello,

Swift 4.2 is coming with the v3.0 (https://github.com/floriangbh/FacebookImagePicker/projects/1). Otherwise it seems to me that Swift 4.2 is actually not mandatory to build you project with Xcode 10 :)

**Comment by floriangbh** [comment]
v2.5.0 is now available
