### ISSUE TITLE
Problem with iOS 13

### ISSUE THREAD

**Issue by EkilDeew** [floriangbh/FacebookImagePicker#55]
When presenting the view with iOS 13 the picker is instantly dismissed.

`didFailWithError` is not called though. Only `didCancel` is instantly called.

**Comment by floriangbh** [comment]
Hello @EkilDeew, 

Thanks for the report. This year I'm not planing to install any beta since the release candidate is released, so I can't reproduce this issue at this time...

**Comment by EkilDeew** [comment]
I'll try to fill a PR if I find the time !

**Comment by floriangbh** [comment]
It's seem to be a FBSDKs related issue. The login always pass in the `response?.is Cancelled == true` sequence.

**Comment by EkilDeew** [comment]
You're right, disconnected from FB on my app, tried to reconnect and now I get the same error as yours.. You can close the issue I guess !

**Comment by floriangbh** [comment]
Should be fix with the 5.2 release : https://github.com/facebook/facebook-objc-sdk/blob/master/CHANGELOG.md?fbclid=IwAR0sNWY0AUMViWbx_aspD3f_Bc_nTXiCDR3EnGR3E4WQOlkraFTXpiUt0cQ#520

I will update the library asap :-)
