### ISSUE TITLE
Profile picture not loading on first click

### ISSUE THREAD

**Issue by pradeepkatiyar** [floriangbh/FacebookImagePicker#56]
After login facebook all album loaded but when click on profile picture then images are not loading on first click as same happens for timeline photos loader is spinning as long as have open the screen but go back and once again click on profile picture then images loaded. FIrst time user experience goes very bad. Find my attachment
![WhatsApp Image 2019-07-29 at 12 28 18](https://user-images.githubusercontent.com/5916740/62027919-90c1b680-b1fc-11e9-97c4-46d8b80dea59.jpeg)

**Comment by floriangbh** [comment]
Hello @pradeepkatiyar, 

I'll take look on it asap, thanks for the report !

**Comment by floriangbh** [comment]
I can't reproduce this issue and I have lost my facebook test account with a large amount of picture. Can you provide more information to reproduce this ? (number of pictures for example)

**Comment by pradeepkatiyar** [comment]
Please have a look video

https://youtu.be/-Iuky1BO_nQ

**Comment by pradeepkatiyar** [comment]
I have installed lib via pod 

pod 'GBHFacebookImagePicker'


Please find below my code


func getFbImage(){
      let picker = FacebookImagePicker()
      picker.presentFacebookAlbumImagePicker(from: self, delegate: self)   
}
               
extension ProfileViewController: FacebookImagePickerDelegate {
    
    func facebookImagePicker(
        imagePicker: UIViewController,
        successImageModels: [FacebookImage],
        errorImageModels: [FacebookImage],
        errors: [Error?]
        ){
        DispatchQueue.main.async {
            if successImageModels.count > 0 {
                self.arrPics.append(successImageModels[0])
            }
            self.collectionView.reloadData()
        }
    }
    
    /// Called when facebook picker failed
    
    func facebookImagePicker(imagePicker: UIViewController,
                             didFailWithError error: Error?){
        print("Cancelled Facebook Album picker with error")
        print(error.debugDescription)
    }
    
    /// Called when facebook picker is cancelled without error
    func facebookImagePicker(didCancelled imagePicker: UIViewController){
         print("Cancelled Facebook Album picker")
    }
    
    /// Called when image picker completed dismissing
    func facebookImagePickerDismissed(){
        print("Dismissed Facebook Album picker")
    }
   
}

**Comment by floriangbh** [comment]
Are you on the last version ? 
It seems to be the same issue as https://github.com/floriangbh/FacebookImagePicker/issues/54, but it's now fixed on the v3.1.0.

**Comment by pradeepkatiyar** [comment]
Thanks, i have update all related lib and fixed the issue.
