### ISSUE TITLE
Type 'SelectPhotosViewController' does not conform to protocol 'FacebookImagePickerDelegate'

### ISSUE THREAD

**Issue by michaeldebo** [floriangbh/FacebookImagePicker#57]
Hi,
I get the error found in the title even though I add the protocol subs to fix it, but then the same error comes back.

This is what's not recognized as part of the protocol even though it's what the autocomplete fills in:

    func facebookImagePicker(imagePicker: UIViewController, successImageModels: [FacebookImage], errorImageModels: [FacebookImage], errors: [Error?]) {
        allPhotos.append(contentsOf: successImageModels)
        collectionView.reloadData()
    }

I'm running the most recent version of all pods.

How do I fix this?

**Comment by michaeldebo** [comment]
When I try cleaning the project and derived data, then rebuilding it doesn't work. It starts as a does not recognize the FBSDKCore module in the problematic view controller specifically, then morphs into this error that I have not been able to fix.

**Comment by floriangbh** [comment]
Hello @michaeldebo,
It seems to be an error with cocoapods and your project.
Did you try to `pod deintegrate` and `pod install` ? 
Can you post the result of your `pod install` ? 
Thanks

**Comment by michaeldebo** [comment]
I tried pod deintegrate then pod install. it didn't fix the problem. here's the what the terminal said upon pod install:

Michaels-MBP:Revibe michaeldeboisblanc$ pod install
Analyzing dependencies
Downloading dependencies
Installing BoringSSL-GRPC (0.0.3)
Installing FBSDKCoreKit (5.2.3)
Installing FBSDKLoginKit (5.2.3)
Installing Firebase (6.6.0)
Installing FirebaseAnalytics (6.1.0)
Installing FirebaseAuth (6.2.2)
Installing FirebaseAuthInterop (1.0.0)
Installing FirebaseCore (6.2.0)
Installing FirebaseCoreDiagnostics (1.0.1)
Installing FirebaseCoreDiagnosticsInterop (1.0.0)
Installing FirebaseFirestore (1.4.3)
Installing FirebaseFunctions (2.5.1)
Installing FirebaseInstanceID (4.2.3)
Installing GBHFacebookImagePicker (3.1.0)
Installing GTMSessionFetcher (1.2.2)
Installing GoogleAppMeasurement (6.1.0)
Installing GoogleDataTransport (1.1.0)
Installing GoogleDataTransportCCTSupport (1.0.1)
Installing GoogleUtilities (6.2.4)
Installing Protobuf (3.9.0)
Installing SDWebImage (5.1.0)
Installing gRPC-C++ (0.0.9)
Installing gRPC-Core (1.21.0)
Installing leveldb-library (1.20)
Installing nanopb (0.3.901)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 9 dependencies from the Podfile and 25 total pods installed.

[!] Automatically assigning platform `ios` with version `10.3` on target `Revibe` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

**Comment by michaeldebo** [comment]
Do you think upgrading to swift 5.0 or 5.1 would fix this?

**Comment by floriangbh** [comment]
No I don’t think this is a Swift version issue. I can’t really help you without seeing the project sorry.

**Comment by michaeldebo** [comment]
Does seeing this part of the code for my view controller that has the problems help?

import UIKit
import FBSDKCoreKit
import FBSDKLoginKit
import GBHFacebookImagePicker

class SelectPhotosViewController: UIViewController, UICollectionViewDataSource, UICollectionViewDelegate {
    
    private var album: FacebookAlbum?
    private var allPhotos = [FacebookImage]()
    private var albumList: [FacebookAlbum] = []

//======//

extension SelectPhotosViewController: FacebookImagePickerDelegate {
    
    func facebookImagePicker(imagePicker: UIViewController, successImageModels: [FacebookImage], errorImageModels: [FacebookImage], errors: [Error?]) {
        allPhotos.append(contentsOf: successImageModels)
        collectionView.reloadData()
    }

    func facebookImagePicker(imagePicker: UIViewController, didFailWithError error: Error?) {
        print("Cancelled Facebook Album picker with error")
        print(error.debugDescription)
    }

    // Optional
    func facebookImagePicker(didCancelled imagePicker: UIViewController) {
        print("Cancelled Facebook Album picker")
    }

    // Optional
    func facebookImagePickerDismissed() {
        print("Picker dismissed")
    }

}

**Comment by floriangbh** [comment]
I don't see any problem with this code. Your problem seems to be specific to your project and your cocoapods configuration. You can try to implement a sample app with this library to check if you want.

**Comment by floriangbh** [comment]
@michaeldebo, did you solve this issue ?

**Comment by michaeldebo** [comment]
No, I had to make a collection view of all fb photos. Yours was better but I couldn’t get it to work.
