### ISSUE TITLE
Expose the GBHFacebookNavigationController

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [floriangbh/FacebookImagePicker#59]
Hi,

Would it be possible to expose the `GBHFacebookNavigationController` instance. Maybe in the `func facebookImagePicker(imagePicker: UIViewController, successImageModels: [GBHFacebookImage], errorImageModels: [GBHFacebookImage], errors: [Swift.Error?])` method.

Like in `UIImagePickerController`, the `picker` in the method `func imagePickerController(_ picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [String: Any])` allows access to its navigation controller.

If I wanted to push another view controller myself after selecting an image, for example to crop the selected image, this could be useful.

**Comment by floriangbh** [comment]
Hello,

Why not ! But I don't have time at this moment. 
Feel free to make a PR if you have some time :-)
