### ISSUE TITLE
GBHFacebookImageModel to  GBHFacebookImage

### ISSUE THREAD

**Issue by frelei** [floriangbh/FacebookImagePicker#9]
Hey  @terflogag ,

What do you think to change the name to GBHFacebookImage? 
I think we don't need explicit say that it's a model.

So in the delegate we will have something like
`func facebookImagePicker(imagePicker: UIViewController, didSelect: GBHFacebookImage)`

**Comment by floriangbh** [comment]
Hey @frelei, 

Yes why not, but if I doing that for the image, I need to do it for album also (even if it's private model). I will do it for the 2.0 in January :) 

Thanks for this issue :)
